# Generated by Django 6.0.1 on 2026-02-03 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0002_alter_sp_couches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Спортивный разряд')),
            ],
            options={
                'verbose_name': 'Спортивный разряд',
                'verbose_name_plural': 'Спортивные разряды',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='sp',
            options={'ordering': ['name'], 'verbose_name': 'спортсмена', 'verbose_name_plural': 'Спортсмены'},
        ),
        migrations.AlterField(
            model_name='sp',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='sp',
            name='couches',
            field=models.TextField(verbose_name='Тренерский состав'),
        ),
        migrations.AlterField(
            model_name='sp',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='sp',
            name='town',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='sp',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sportsman.category', verbose_name='Спортивный разряд'),
        ),
    ]
