# Generated by Django 6.0.1 on 2026-02-03 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0003_category_alter_sp_options_alter_sp_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name_rank'], 'verbose_name': 'Спортивный разряд', 'verbose_name_plural': 'Спортивные разряды'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_rank',
        ),
        migrations.AlterField(
            model_name='sp',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sportsman.category', verbose_name='Разряд'),
        ),
    ]
