# Generated by Django 6.0.1 on 2026-02-03 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0004_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp',
            name='category1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sportsman.category', verbose_name='Разряд'),
        ),
        migrations.AlterField(
            model_name='sp',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Разряд'),
        ),
    ]
