# Generated by Django 6.0.1 on 2026-02-03 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0005_sp_category1_alter_sp_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sp',
            name='category1',
        ),
        migrations.AlterField(
            model_name='sp',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sportsman.category', verbose_name='Разряд'),
        ),
    ]
