# Generated by Django 6.0.1 on 2026-02-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0008_news_newsimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='image_news',
        ),
    ]
