# Generated by Django 6.0.1 on 2026-02-19 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0010_rubric_subrubric_superrubric_rubric_super_rubric'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsimage',
            options={'verbose_name': 'Дополнительная иллюстрация', 'verbose_name_plural': 'Дополнительные иллюстрации'},
        ),
        migrations.AddField(
            model_name='news',
            name='rubric',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='sportsman.subrubric', verbose_name='Рубрика'),
            preserve_default=False,
        ),
    ]
