# Generated by Django 6.0.1 on 2026-02-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0011_alter_newsimage_options_news_rubric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='rubric',
            field=models.CharField(max_length=40, verbose_name='Рубрика'),
        ),
    ]
