# Generated by Django 6.0.1 on 2026-02-19 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0012_alter_news_rubric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sportsman.subrubric', verbose_name='Рубрика'),
        ),
    ]
