# Generated by Django 6.0.1 on 2026-02-23 09:33

import django.db.models.deletion
import sportsman.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0013_alter_news_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp',
            name='image_sp',
            field=models.ImageField(blank=True, upload_to=sportsman.utilities.get_timestamp_path, verbose_name='Фотография'),
        ),
        migrations.CreateModel(
            name='SPImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_sp', models.ImageField(upload_to=sportsman.utilities.get_timestamp_path, verbose_name='Фотография')),
                ('sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsman.sp', verbose_name='Спортсмен')),
            ],
            options={
                'verbose_name': 'Дополнительная фотография',
                'verbose_name_plural': 'Дополнительные фотографии',
            },
        ),
    ]
